import { asset } from '@/lib/asset'

/**
 * The King James Version — public domain, so the full text ships as static
 * JSON under `public/bible/` (generated by `scripts/build-bible-data.mjs`)
 * rather than a dependency or a network call. It's fetched lazily rather
 * than imported, so the ~4 MB of verse text never lands in the JS bundle or
 * the initial page load — only players who open the Bible screen pay for
 * it, once, and the service worker's generic runtime cache (`public/sw.js`)
 * keeps it offline after that first fetch.
 */

export interface BibleBook {
  name: string
  testament: 'old' | 'new'
  chapters: number
}

/** `verses[bookIndex][chapterIndex][verseIndex]` — book/chapter/verse numbers
 *  are the array indices, so nothing repeats the reference itself. */
export type BibleVerses = string[][][]

export interface BibleData {
  books: BibleBook[]
  verses: BibleVerses
}

let cached: Promise<BibleData> | null = null

/** Cached across calls so navigating away from and back to the Bible screen
 *  never re-fetches — the browser/service-worker cache still saves the
 *  network round trip either way, but this also skips the JSON re-parse. */
export function loadBibleData(): Promise<BibleData> {
  cached ??= Promise.all([
    fetch(asset('bible/books.json')).then((r) => r.json() as Promise<BibleBook[]>),
    fetch(asset('bible/kjv.json')).then((r) => r.json() as Promise<BibleVerses>),
  ]).then(([books, verses]) => ({ books, verses }))
  return cached
}

export interface SearchResult {
  bookIndex: number
  book: string
  chapter: number
  verse: number
  text: string
}

/** Plain case-insensitive substring search across every verse. Stops the
 *  moment `limit` results are found rather than scanning all 31,000 verses
 *  every time — a search screen only ever shows the first page anyway. */
export function searchVerses(data: BibleData, query: string, limit = 80): SearchResult[] {
  const needle = query.trim().toLowerCase()
  if (needle.length < 2) return []

  const results: SearchResult[] = []
  for (let bookIndex = 0; bookIndex < data.books.length && results.length < limit; bookIndex++) {
    const chapters = data.verses[bookIndex]!
    for (let chapter = 0; chapter < chapters.length && results.length < limit; chapter++) {
      const versesInChapter = chapters[chapter]!
      for (let verse = 0; verse < versesInChapter.length && results.length < limit; verse++) {
        const text = versesInChapter[verse]!
        if (text.toLowerCase().includes(needle)) {
          results.push({
            bookIndex,
            book: data.books[bookIndex]!.name,
            chapter: chapter + 1,
            verse: verse + 1,
            text,
          })
        }
      }
    }
  }
  return results
}
